//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAILY_CONSUMPTION
    {
        public string DESCRIPTION { get; set; }
        public decimal AMMOUNT { get; set; }
        public Nullable<System.DateTime> DATES { get; set; }
    }
}
