//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP
    {
        public string EMP_ID { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_PHONE { get; set; }
        public decimal EMP_SALARY { get; set; }
        public decimal EMP_DEDUCTION { get; set; }
    }
}
