//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventoryEntities : DbContext
    {
        public inventoryEntities()
            : base("name=inventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DAILY_SELL> DAILY_SELL { get; set; }
        public DbSet<EMP> EMPs { get; set; }
        public DbSet<ORDER_INFO> ORDER_INFO { get; set; }
        public DbSet<BIN_izCQ6CO8RfujP83PIhZXUw___0> BIN_izCQ6CO8RfujP83PIhZXUw___0 { get; set; }
        public DbSet<DAILY_CONSUMPTION> DAILY_CONSUMPTION { get; set; }
        public DbSet<ITEM_ORDER> ITEM_ORDER { get; set; }
    }
}
