//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_ORDER
    {
        public string ORDER_NO { get; set; }
        public string TYPE { get; set; }
        public decimal AMMOUNT { get; set; }
    
        public virtual ORDER_INFO ORDER_INFO { get; set; }
    }
}
