//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_INFO
    {
        public ORDER_INFO()
        {
            this.ITEM_ORDER = new HashSet<ITEM_ORDER>();
        }
    
        public string ORDER_NO { get; set; }
        public decimal AMOUNT { get; set; }
        public decimal ADVANCE { get; set; }
        public decimal DUE { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public string CONTACT_NO { get; set; }
    
        public virtual ICollection<ITEM_ORDER> ITEM_ORDER { get; set; }
    }
}
